#! /bin/sh

sxhkd &

bspc monitor -d I II III IV V VI VII VIII IX X
if [ $(xrandr | grep 'DP-1-2\|DP-1-3' | wc -l) == "2" ]
then
	bspc monitor DP-1-3 -d I II III IV V
	bspc monitor DP-1-2 -d VI VII VIII IX X
elif xrandr | grep 'HDMI-1 connected primary 2560x1080'
then
	bspc monitor HDMI-1 -d I II III IV V
	bspc monitor eDP-1 -d VI VII VIII IX X
fi

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
